### PR TITLE
fix: formatted durations

### PR DESCRIPTION
**Pull request by antoniomuso**
## 🚨 Proposed changes

I formatted the durations with the following format: 
image

## ⚙️ Types of changes

What types of changes does your code introduce? _Put an `x` in the boxes that apply_

-   [ ] New feature (non-breaking change which adds functionality)
-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation Update (if none of the other choices apply)
-   [ ] Refactor

### CODE REVIEW

**Review by JellyBellyDev — APPROVED** [review]
🚀

**Review by simonecorsi — COMMENTED** [review]
Can't we use `dayjs` instead of `moment`? Is lighter on the bundle

**Comment by antoniomuso** [comment]
Yes, we can. But I prefer to do this in a separated PR. It is a low priority.

**Comment by simonecorsi** [comment]
It's ok for me to move on another issue #13, but it won't take long to swap it the API is very similar.

**Review by simonecorsi — APPROVED** [review]

**Pull request merged**
