### PR TITLE
chore: removed moment and added dayjs

### PR DESCRIPTION
**Pull request by antoniomuso**
## 🚨 Proposed changes

Migrated to dayjs.

close https://github.com/immobiliare/backstage-plugin-gitlab/issues/13

## ⚙️ Types of changes

What types of changes does your code introduce? _Put an `x` in the boxes that apply_

-   [ ] New feature (non-breaking change which adds functionality)
-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation Update (if none of the other choices apply)
-   [ ] Refactor

### CODE REVIEW

**Review by JellyBellyDev — APPROVED** [review]
LGTM

**Review by simonecorsi — APPROVED** [review]
Nice job 🚀

**Pull request merged**
