### PR TITLE
feat: added code ownership

### LINKED ISSUE #16: Add card to handle CODEOWNERS standard
We can add a card to handle CODEOWNER standard using gitlab API.

The possible gitlab API can be: `api/v4/projects/:id/repository/files/CODEOWNERS?ref=master`

### PR DESCRIPTION
**Pull request by antoniomuso**
## 🚨 Proposed changes

close #16 

## ⚙️ Types of changes

What types of changes does your code introduce? _Put an `x` in the boxes that apply_

-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation Update (if none of the other choices apply)
-   [ ] Refactor

### CODE REVIEW

**Review by simonecorsi — COMMENTED** [review]
Would be nice to have a screenshot of the feature in the README where it's explained

**Comment by antoniomuso** [comment]
Done!

**Review by simonecorsi — APPROVED** [review]

**Review by JellyBellyDev — APPROVED** [review]
LGTM 👍

**Pull request merged**
